//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партия()
        {
            this.Продукт_Партия = new HashSet<Продукт_Партия>();
        }
    
        public int Код_Партии { get; set; }
        public Nullable<System.DateTime> Дата_Производства { get; set; }
        public Nullable<System.TimeSpan> Время_Производства { get; set; }
        public int Код_Склада { get; set; }
        public Nullable<int> Код_Клиента { get; set; }
        public Nullable<System.DateTime> Дата_Отгрузки { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Склад Склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продукт_Партия> Продукт_Партия { get; set; }
    }
}
