//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукт_Партия
    {
        public int Код_Продукта { get; set; }
        public int Код_Партии { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Партия Партия { get; set; }
        public virtual Продукт Продукт { get; set; }
    }
}
